### ISSUE TITLE
FR: Report product is current

### ISSUE THREAD

**Issue by andrew-kelley-brautomation** [ChrisHairstonBnR/Python-Successor-Finder#2]
Current products show as no successor available. They should instead report that they are a current product.
![image](https://user-images.githubusercontent.com/116588621/224127546-6a267404-e8de-4407-8212-7481bfcf30a1.png)

**Comment by ChrisHairstonBnR** [comment]
I do not plan to implement letting the customer know that the entered material is not obsolete. It is assumed that the user is using this program because they've already discovered or been told that the material is obsolete. The B&R website (logged in) is the quickest way to check the production status of a material.
